name: Ruff Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # ajuste si besoin

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff Lint
        run: ruff check .

      - name: Run Ruff Format Check
        run: ruff format --check .
